### ISSUE TITLE
[Bug] Autoplay between chapters doesn't always work

### ISSUE THREAD

**Issue by dspacejs** [geigi/cozy#348] opened 2020-10-04 00:14 UTC
### Bug description

It doesn't always work for some reason. Other times it does.

### Steps to reproduce

I don't know how to reproduce it.

### System Information

- Operating System: Ubuntu 20.04.1 LTS
- Installation source: `flatpak`
- Version of cozy: 0.7.2

**Comment by geigi** [comment] 2020-10-04 13:44
Thanks for reporting :) I could not reproduce this issue yet. Could you send me Cozy's log file when this happens again?
Cou can find it here:
```
~/.var/app/com.github.geigi.cozy/data/cozy/cozy.log
```

**Comment by geigi** [comment] 2020-11-14 10:08
I'm closing the issue for now to keep a better overview. Please reopen it when you encounter it again! :)

**Closed by geigi** 2020-11-14 10:08 UTC
Labels: bug
