### ISSUE TITLE
No hapters supported in m4a-files

### ISSUE THREAD

**Issue by rakor** [geigi/cozy#161] opened 2019-08-10 15:12 UTC
### Bug/Feature description
I have some audiobooks as m4a, where the whole audiobook is one file, but has chapters. Cozy does not show the chapters, but displays the file as one big audiofile.

### Steps to reproduce
Import a m4a-file with chapters

### System Information
- Operating System: 
Bebian Buster
- Installation source: 
Flathub
- Version of cozy: 
0.6.7

**Comment by not7cd** [comment] 2020-05-23 19:15
I believe that this is a duplicate of #62 since m4a and m4b are MPEG-4 containers and probably contain similar metadata.

**Comment by geigi** [comment] 2020-05-24 16:57
Yes it quite sure is. When m4b is supported m4a chapters will be also :)

**Closed by geigi** 2020-05-24 16:57 UTC

**Comment by not7cd** [comment] 2020-05-25 08:44
Let's label this as duplicate, so it will be easier to browse through issues

**Comment by AinaSG** [comment] 2024-01-17 18:54
Hi! I Was trying to see why the chapters in my .m4a file where not showing and I found this issue.

I see that the related ticket has been closed and Cozy supports now chapters for .m4b so I changed my .m4a to .m4b and all works as expected. I think that it would be great if you could make it so the .m4a are imported through the same path as .m4b (its the same format just for "audio" instead of "books" but a lot of shops use that one). 

Thank you very much!
