### ISSUE TITLE
Book progress lost on shutdown/crash + add option to save progress at time intervals instead of just on close

### ISSUE THREAD

**Issue by chucktdriscoll** [geigi/cozy#657] opened 2021-09-30 13:14 UTC
### Bug/Feature description
When I shutdown/reboot my computer with cozy running on next launch cozy remembers what book was being played, but not the position, it starts the whole book over.  While this is likely an issue with my system failing to signal programs to end correctly thus not giving cozy the opportunity to write out the progress I feel that adding a configuration option to save progress at intervals rather than just at program termination would help both in this case and in cases where cozy or the system crash.  Saving progress every 30s or 60s shouldn't create a great IO burden and would save me from having to spend an obnoxious amount of time hunting for the approximate place in the book I was.

### Steps to reproduce
Shutdown computer with cozy running (or have cozy/computer crash)

### System Information
- Operating System: Gentoo/KDE Plasma
- Installation source: local build from git
- Version of cozy: 1.1.2

**Comment by geigi** [comment] 2022-01-08 17:02
Have you experienced this bug again? I can't reproduce this issue and without the log file I'm unfortunately unable to help you. Otherwise I'm going to close this issue due to missing information...

**Comment by geigi** [comment] 2022-02-27 16:17
I'll close this due to missing information.

**Closed by geigi** 2022-02-27 16:17 UTC
