### ISSUE TITLE
[Bug] Play/pause button not able to toggle

### ISSUE THREAD

**Issue by dspacejs** [geigi/cozy#345] opened 2020-10-03 23:32 UTC
### Bug description

Clicking the play/pause button enables you to play the audiobook, but not pause it. To pause it you have to press `Space`. 

### Steps to reproduce

1. Play an audiobook by clicking the play button in the top bar
2. Click it again to pause it, it shouldn't work
3. Press `Space` to pause it, it should work

### System Information
- Operating System: Ubuntu 20.04.1 LTS
- Installation source: `flatpak`
- Version of cozy: 0.7.2

**Comment by geigi** [comment] 2020-10-04 13:51
Thanks for reporting :) (Same text as in the other issue ;) ) I could not reproduce this issue yet. Could you send me Cozy's log file when this happens again?
You can find it here:
```
~/.var/app/com.github.geigi.cozy/data/cozy/cozy.log
```

**Comment by dspacejs** [comment] 2020-10-06 03:19
@geigi hmm, it seems to be working for me too, now. Hopefully the bug shows up again

**Comment by geigi** [comment] 2020-11-14 10:09
I'm closing the issue for now to keep a better overview. Please reopen it when you encounter it again! :)

**Closed by geigi** 2020-11-14 10:09 UTC
Labels: bug
