### ISSUE TITLE
Unable to get flatpak version to accept a selected folder

### ISSUE THREAD

**Issue by AlbeyAmakiir** [geigi/cozy#482] opened 2021-05-15 17:02 UTC
### Bug/Feature description
After running for the first time, or later in the preferences, when I try and add or change a storage location, I can navigate my filesystem just fine, but the "Open" button does nothing when clicked. Running `flatpak --user override --filesystem=/home/my-username/books/audio com.github.geigi.cozy` doesn't seem to have any effect compared to without.

### Steps to reproduce
- New install of flatpak version.
- Open the dropdown for storage location, and click _Other..._
- Find a suitable folder, and click _Open_ to accept. The button visibly clicks in, but nothing changes. The folder window remains, and can still be navigated, and the setting hasn't been altered.

### System Information
- Operating System: openSUSE Leap 15.2, 64-bit, KDE Plasma 5.18.6
- Installation source: flatpak
- Version of cozy: 0.9.5 (stable)

It works on Cozy 0.6.7, the version on the openSUSE repos. Not sure what's different about my situation, but I would have assumed if it was widespread that it would have been reported by now.

**Comment by geigi** [comment] 2021-05-15 17:19
Hi! Thanks for reporting.

I just tried to reproduce this issue but I couldn't.
On a fresh installation of the Flatpak version 0.9.5 I can select a book containing audiobooks in the main window or the settings window and Cozy starts importing the files.

Could you post Cozy's log file here after trying to select a folder and closing Cozy?
You can find the log file (for the Flatpak version) here:
```
~/.var/app/com.github.geigi.cozy/data/cozy/cozy.log
```

**Comment by AlbeyAmakiir** [comment] 2021-05-16 07:51
```
17:46:28 [MainThread  ] [applicatio] [INFO ]  ('org.gnome.platform', '40', 'Flatpak runtime')
17:46:28 [MainThread  ] [applicatio] [INFO ]  Starting up cozy 0.9.5
17:46:28 [MainThread  ] [db        ] [INFO ]  SQLite version: 3.32.1
17:46:31 [MainThread  ] [applicatio] [INFO ]  libhandy version: 1
17:46:32 [MainThread  ] [ui        ] [INFO ]  Initialize main window
17:46:42 [Thread-11   ] [offline_ca] [INFO ]  Started processing queue
17:46:42 [MainThread  ] [gst_player] [ERROR]  Could not determine volume because player is not loaded.
17:46:42 [MainThread  ] [gst_player] [ERROR]  Could not set volume because player is not loaded.
17:47:10 [MainThread  ] [ui        ] [INFO ]  Closing.
17:47:10 [MainThread  ] [gst_player] [INFO ]  Dispose
17:47:10 [MainThread  ] [db        ] [INFO ]  Closing.
17:47:10 [MainThread  ] [ui        ] [INFO ]  Closing app.
17:47:10 [MainThread  ] [gst_player] [INFO ]  Dispose
17:47:10 [MainThread  ] [ui        ] [INFO ]  App closed.
```

This is identical whether I run the flatpak folder command or not.

**Comment by geigi** [comment] 2021-05-19 20:22
Ok this is a bit weird. Cozy is not catching any error. It looks like the problem could be within the file selector dialog itself. I'm not quite sure how to debug this further ...

**Comment by AlbeyAmakiir** [comment] 2021-05-20 07:25
Weird, since it doesn't fail anywhere else. But yeah, I'm not sure how to move forward, either.
I'll let you know if, when openSUSE eventually updates the repo package, that works or fails, too. Might be a thing in my flatpak setup for all I know, as I rarely use it. :/
Thanks for responding, though.

**Comment by geigi** [comment] 2021-05-20 15:02
It's possible that it only happens in flatpak applications because the GTK SDK is shipped as dependency of Flatpak Apps separately (and does not come from your OS). Do you have any flatpak updates available?

**Comment by geigi** [comment] 2021-05-20 15:03
Maybe this doesn't help but the latest version of Cozy is available for openSUSE Tumbleweed: https://software.opensuse.org/package/cozy

**Comment by AlbeyAmakiir** [comment] 2021-05-21 12:11
Turns out it's a KDE bug. https://bugs.kde.org/show_bug.cgi?id=419874

Was fixed like 5 days ago, and not yet included in any releases. (And Leap doesn't get latest releases very often. Maybe I *should* switch to Tumbleweed...) But I think there's a workaround.

According to the commit (below), it sounds like there's a specific mode you have to set, at least when using Flatpak? Looks like the commit makes it work without the mode:

> Removes the restriction on not being able to select directories in KFileWidget. If user selects a directory but isn't in directory mode, then slotOk will take care of it.
Required for folder selection via xdg-desktop-portal-kde (eg in Firefox, Flatpaks, etc) to work properly.

https://invent.kde.org/frameworks/kio/commit/0829537a46c4fb2d907ab5c383fda041786175df

So, for it to work better from flatpack on KDE before the fix comes out, it sounds like you'd have to specifically set the mode of the file selector to want a directory. At least, if I understand correctly.

**Comment by geigi** [comment] 2021-05-21 13:09
Oh ok I see. Thanks for the update!

Maybe there is something I can do on Cozy's side but I'm not sure. The file chooser is configured for directory selection only using the property that is designed for it, so I'm not doing any custom magic here :) But maybe I do find some hints in the bug tracker you send me or in the projects that also do have this issue and are mentioned in the bug tracker :)

**Comment by rdbende** [comment] 2024-01-05 13:18
Closing, as no longer relevant.

**Closed by rdbende** 2024-01-05 13:18 UTC
