### ISSUE TITLE
Prevents Lock Screen or Suspend

### ISSUE THREAD

**Issue by rinav** [geigi/cozy#109] opened 2018-05-04 14:05 UTC
I just discovered that if the app is open and in paused state; and
I close the laptop lib or manually using the GUI to lock the screen, It does not allow it.

If I close the app and then try the above steps, every thing works fine.

I am using Manjaro - Deepin Linux with 4.16 Kernel.
Do let me know if more info or logs need to be pulled.

Thankyou for awesome app :)

**Comment by geigi** [comment] 2018-05-06 16:39
Are you running the flatpak version or is cozy packaged for deepin? Also which version of cozy are you running?

**Comment by rinav** [comment] 2018-05-07 13:58
I am not using flatpack. I used aur package to install the app.
[Aur - Cozy ](https://aur.archlinux.org/packages/cozy-audiobooks)

I am using version: 0.5.5

**Comment by geigi** [comment] 2018-06-01 18:00
I cannot reproduce this issue on other distros. Could you post the cozy log 
```
~/.local/share/cozy/cozy.log
```
Here after you started and paused playback and closing and opening the lid?

**Comment by rinav** [comment] 2018-06-02 07:44
It's not producing any logs,
here's what I have. I started, paused, closed lid etc; but no logs
are there any switches that needs to be enable to debug or get the verbose logs?

```
cat cozy.log
13:09:10 [MainThread  ] [main      ] [INFO ]  ('arch', 'Manjaro', 'Linux')
13:09:10 [MainThread  ] [main      ] [INFO ]  Starting up cozy 0.5.5
13:09:11 [MainThread  ] [ui        ] [INFO ]  Initialize main window
```

**Comment by geigi** [comment] 2018-06-02 13:30
Ok, I wondered if there is an exception happening while releasing the wake lock on your system, it would've been in the log file. There is an debug option, just launch cozy with 
```
-d
```
You can try this but most likely there won't be any useful information in there... 
Which desktop environment are you using?

**Closed** 2019-07-05 16:31 UTC
Labels: bug
