### ISSUE TITLE
Dark Mode not working

### ISSUE THREAD

**Issue by leighss** [geigi/cozy#140] opened 2018-11-16 10:34 UTC
### Bug/Feature description
Switched to 'Dark Mode' but remains light
### Steps to reproduce
Switched to 'Dark Mode' in Advanced Settings, but app appearance remains light
### System Information
- Operating System: Xubuntu 18.04 (arc-theme & moka-icon-theme)
- Installation source: Flatpak
- Version of cozy: 0.6.1b

**Comment by leighss** [comment] 2018-11-16 10:57
Thanks,
Not sure if this is of help (or even if similarities with Cozy are deeper than just appearance) but Lollypop on same machine already appears with a dark theme without switching to 'Use dark theme variant'.

**Comment by geigi** [comment] 2019-12-23 09:29
I just tried to reproduce this issue with cozy 0.6.10 on flatpak but switching to dark mode with arc theme was working. I'm closing this issue now because it is so old. Let me know when the problem still persists :)

**Closed by geigi** 2019-12-23 09:29 UTC
Labels: bug
