### ISSUE TITLE
Add appdata to be translated

### ISSUE THREAD

**Issue by NathanBnm** [geigi/cozy#148] opened 2019-01-24 21:15 UTC
Translating `appdata.xml` file will help people to know about your app in the AppCenter. For example mostly French users won't download the app if it's description is in English, 'cause they will think that the app isn't translated and won't take time to read if its not translated.

**Comment by geigi** [comment] 2019-01-25 08:31
Thanks, a very good suggestion! I'll have a look into this.

**Comment by NathanBnm** [comment] 2019-03-27 13:11
@geigi I tried to do that but I can't build the app. Here is the error message I get:

```
Traceback (most recent call last):
  File "/usr/bin/com.github.geigi.cozy", line 35, in <module>
    from cozy.ui import CozyUI
  File "/usr/lib/python3/dist-packages/cozy/ui.py", line 8, in <module>
    from cozy.book_element import BookElement
  File "/usr/lib/python3/dist-packages/cozy/book_element.py", line 4, in <module>
    import cozy.db as db
  File "/usr/lib/python3/dist-packages/cozy/db.py", line 7, in <module>
    from peewee import __version__ as PeeweeVersion
ModuleNotFoundError: No module named 'peewee'
```

**Comment by geigi** [comment] 2019-03-30 09:27
Do you have the package `python3-peewee` or `python-peewee` installed?

**Comment by NathanBnm** [comment] 2019-03-30 10:17
You should add these names instead of just `pewee` 'cause I didn't find the name of the package.

**Comment by NathanBnm** [comment] 2019-03-30 10:18
I can't install theses with `sudo apt install`. Can you help?

**Comment by geigi** [comment] 2019-03-30 11:07
If they are not available with apt your ubuntu or debian is too old. They are only included with newer versions.
Instead you need to install peewee with `pip3` (install `python3-pip` if not available).
`pip3 install peewee`

**Comment by NathanBnm** [comment] 2019-03-30 11:40
But, actually I have elementary OS 5 Juno, based on Ubuntu 18.04 Bionic Beaver, that's not old :open_mouth:.

I'm going to try this.

**Comment by NathanBnm** [comment] 2019-03-30 11:48
I just installed `pip3` and now this is the message I get when I try to install `pewee`:

```
$ pip3 install pewee
Collecting pewee
  Could not find a version that satisfies the requirement pewee (from versions: )
No matching distribution found for pewee
```

**Comment by geigi** [comment] 2019-03-30 11:49
Oh ok, then the package should be available. You can try enabling the universe package repository: `sudo add-apt-repository universe`
You have a typo, its called `peewee` not `pewee`.

**Comment by NathanBnm** [comment] 2019-03-30 12:24
I had a typo right, but now I have this error when I try to launch the app.

```
$ com.github.geigi.cozy 
['/usr/bin/com.github.geigi.cozy']
13:20:30 [MainThread  ] [main      ] [INFO ]  ('elementary', '5.0', 'juno')
13:20:30 [MainThread  ] [main      ] [INFO ]  Starting up cozy 0.6.7
13:20:30 [MainThread  ] [db        ] [ERROR]  Could not connect to database. 
13:20:30 [MainThread  ] [db        ] [ERROR]  Connection already opened.
Traceback (most recent call last):
  File "/usr/bin/com.github.geigi.cozy", line 75, in do_startup
    self.ui.startup()
  File "/usr/lib/python3/dist-packages/cozy/ui.py", line 70, in startup
    self.__init_resources()
  File "/usr/lib/python3/dist-packages/cozy/ui.py", line 79, in __init_resources
    os.path.join(self.pkgdir, 'cozy.ui.gresource'))
GLib.Error: g-file-error-quark: L’ouverture du fichier « /usr/share/com.github.geigi.cozy/cozy.ui.gresource » a échoué : échec de open() : Aucun fichier ou dossier de ce type (4)
13:20:30 [MainThread  ] [ui        ] [INFO ]  Initialize main window
Traceback (most recent call last):
  File "/usr/bin/com.github.geigi.cozy", line 78, in do_activate
    self.ui.activate()
  File "/usr/lib/python3/dist-packages/cozy/ui.py", line 59, in activate
    self.__init_window()
  File "/usr/lib/python3/dist-packages/cozy/ui.py", line 128, in __init_window
    self.window = self.window_builder.get_object("app_window")
AttributeError: 'CozyUI' object has no attribute 'window_builder'
```

**Comment by geigi** [comment] 2019-04-02 18:27
Have you followed the instructions from the readme?

```
$ git clone https://github.com/geigi/cozy.git
$ cd cozy
$ meson desired_build_directory --prefix=desired_installation_directory
$ ninja -C desired_build_directory install
```

To run the app:
```
XDG_DATA_DIRS=desired_installation_directory/share:/usr/share PYTHONPATH=desired_installation_directory/lib/python3.[your_python3_version]/site-packages app/bin/com.github.geigi.cozy
```

**Comment by geigi** [comment] 2019-04-02 18:28
Especially the part where you launch cozy and define the environment variables `XDG_DATA_DIRS` and `PYTHONPATH`

**Comment by NathanBnm** [comment] 2019-04-02 20:19
Oh, my bad, Sorry I didn't see that. I'm going to check when I have time.

**Comment by geigi** [comment] 2019-04-02 21:08
Sorry I hadn't had a lot of time ... A little bit more of explanation: 
python could not find the components for cozy, because it searches only in 
specific folders of the file system. This is also dependent on the 
distribution you use (elementaryos has a different directory than fedora). 
If you're running cozy as a development build, you have to specify where 
python can find the components with those environment variables. The 
directory is the same you used with meson/ninja as the desired installation 
directory. Let me know if you have any questions :)

**Comment by NathanBnm** [comment] 2019-04-06 15:05
Here are the commands I use:
```bash
meson build --prefix=/usr && cd build
ninja install
```
Then I tried to make the app running but it's still not working. I'm not sure about what I have to put in the command:
```bash
XDG_DATA_DIRS=desired_installation_directory/share:/usr/share
```
What do you mean by `desired_installation_directory`, is it `/usr` like in `--prefix=/usr` in the `meson build` command?

I tried with (but it's looking weird to me):

```bash
XDG_DATA_DIRS=/usr/share:/usr/share
```

What is XDG_DATA_DIRS exactly?

Then I tried to put this:

```bash
PYTHONPATH=/usr/lib/python3.6/site-packages 
```
The problem here is that `site-packages` doesn't exist. I have four folders : `python2.7`, `python3`, `python3.6` and `python3.7` and none of them contain anything like this.

Finally I have this (this is where my app seems to be installed):
```bash
/usr/bin/com.github.geigi.cozy
```

**Comment by geigi** [comment] 2019-04-09 06:43
Ok thanks for the detailed description :)

The `--prefix=` defines where cozy should be installed when you run `ninja install`. Therefore I called this `desired_installation_directory`. When I'm running a development build, I don't install cozy to `/usr`, as I always have the latest release installed through the package manager. You can install cozy with this command e.g. to `/home/user/cozy/app` and start it from there. 

`XDG_DATA_DIRS` defines the preference-ordered set of base directories to search for data files. These contain stuff like the translation. If you install cozy to something different than the default installation directory of your linux distribution (e.g. `/home/user/cozy/app`), linux can't find stuff like the translations, because the directory is missing from the `XDG_DATA_DIRS` environment variable. Therefore you have to add it to this environment variable, but only if you install cozy to a directory which is different from the default installation directory of your distribution.

Finally to `PYTHONPATH`: This contains all folders where python searches for code. Most of the cozy code is also in one of those directories. The same principle from `XDG_DATA_DIRS` applies here: If you install cozy somewhere else as the default directory, python is not able to find the cozy code. Additionally as you're running elementaryOS: all Debian based distributions have a different name for the folder `site-packages`: they call it `dist-packages`. Have a look whether this folder exists in your `python3.7` or `python3.6` folders.

Finally I would suggest to install cozy in some directory in your home folder instead of the default installation directory, because this can cause conflicts when you install cozy from App Center or the package manager. Also it is quite useful to see what files cozy installs. Everything that belongs to cozy will be in the e.g. `/home/user/cozy/app` folder.

The commands should look something like this (`bin` is the build directory, `app` the installation directory):
```sh
# This is where you cloned the git repository
cd /home/user/cozy
# create build environment
meson bin --prefix=/home/user/cozy/app
# build cozy
ninja -C bin install
# run cozy, maybe it is python3 or python 3.6 instead of python3.7. Have a look at the directory /home/user/cozy/app/lib/ to find the correct one for you
XDG_DATA_DIRS=/home/user/cozy/app/share:$XDG_DATA_DIRS PYTHONPATH=/home/user/cozy/app/lib/python3.7/dist-packages /home/user/cozy/app/bin/com.github.geigi.cozy
```

I hope this was helpful :) Let me know whether you got this working or not!

**Comment by NathanBnm** [comment] 2019-04-09 08:43
Thank you! This was really helpful :smile: This was very clear and I successfully build the app. Here is the trace. Just take a look if you see something bad.

I'm working on translations now

```bash
nathan@Nathan:~/cozy$ meson bin --prefix=/home/nathan/cozy/appThe Meson build system
Version: 0.49.2
Source dir: /home/nathan/cozy
Build dir: /home/nathan/cozy/bin
Build type: native build
Project name: com.github.geigi.cozy
Project version: 0.6.7
Native C compiler: cc (gcc 7.3.0 "cc (Ubuntu 7.3.0-27ubuntu1~18.04) 7.3.0")
Native Vala compiler: valac (valac 0.40.14)
Build machine cpu family: x86_64
Build machine cpu: x86_64
DEPRECATION: Project targetting '>= 0.40.0' but tried to use feature deprecated since '0.48.0': python3 module
Message: Looking for dependencies
Message: Found python3 binary
Message: Getting python install path
Message: Compiling resources
Found pkg-config: /usr/bin/pkg-config (0.29.1)
Message: Compiling resources
Message: Compiling schemas
Program meson_post_install.py found: YES (/usr/bin/env python3 /home/nathan/cozy/data/meson_post_install.py)
Message: Preparing init file
Configuring com.github.geigi.cozy using configuration
Build targets in project: 11
WARNING: Deprecated features used:
 * 0.48.0: {'python3 module'}
Found ninja-1.8.2 at /usr/bin/ninja
nathan@Nathan:~/cozy$ ninja -C bin installninja: Entering directory `bin'
[4/5] Installing files.
Installing subdir /home/nathan/cozy/data/icons/hicolor to /home/nathan/cozy/app/share/icons/hicolor
Installing /home/nathan/cozy/data/icons/hicolor/scalable/actions/timer-off-symbolic.svg to /home/nathan/cozy/app/share/icons/hicolor/scalable/actions
Installing /home/nathan/cozy/data/icons/hicolor/scalable/actions/download-symbolic.svg to /home/nathan/cozy/app/share/icons/hicolor/scalable/actions
Installing /home/nathan/cozy/data/icons/hicolor/scalable/actions/downloaded-symbolic.svg to /home/nathan/cozy/app/share/icons/hicolor/scalable/actions
Installing /home/nathan/cozy/data/icons/hicolor/scalable/actions/speedometer-symbolic.svg to /home/nathan/cozy/app/share/icons/hicolor/scalable/actions
Installing /home/nathan/cozy/data/icons/hicolor/scalable/actions/timer-on-symbolic.svg to /home/nathan/cozy/app/share/icons/hicolor/scalable/actions
Installing /home/nathan/cozy/data/icons/hicolor/scalable/actions/book-open-variant-symbolic.svg to /home/nathan/cozy/app/share/icons/hicolor/scalable/actions
Installing /home/nathan/cozy/data/icons/hicolor/scalable/apps/com.github.geigi.cozy.svg to /home/nathan/cozy/app/share/icons/hicolor/scalable/apps
Installing /home/nathan/cozy/data/icons/hicolor/48x48/apps/com.github.geigi.cozy.svg to /home/nathan/cozy/app/share/icons/hicolor/48x48/apps
Installing /home/nathan/cozy/data/icons/hicolor/128x128/apps/com.github.geigi.cozy.svg to /home/nathan/cozy/app/share/icons/hicolor/128x128/apps
Installing /home/nathan/cozy/data/icons/hicolor/16x16/apps/com.github.geigi.cozy.svg to /home/nathan/cozy/app/share/icons/hicolor/16x16/apps
Installing /home/nathan/cozy/data/icons/hicolor/64x64/apps/com.github.geigi.cozy.svg to /home/nathan/cozy/app/share/icons/hicolor/64x64/apps
Installing /home/nathan/cozy/data/icons/hicolor/32x32/apps/com.github.geigi.cozy.svg to /home/nathan/cozy/app/share/icons/hicolor/32x32/apps
Installing /home/nathan/cozy/data/icons/hicolor/24x24/apps/com.github.geigi.cozy.svg to /home/nathan/cozy/app/share/icons/hicolor/24x24/apps
Installing subdir /home/nathan/cozy/cozy to /home/nathan/cozy/app/lib/python3/dist-packages/cozy
Installing /home/nathan/cozy/cozy/book_overview.py to /home/nathan/cozy/app/lib/python3/dist-packages/cozy
Installing /home/nathan/cozy/cozy/importer.py to /home/nathan/cozy/app/lib/python3/dist-packages/cozy
Installing /home/nathan/cozy/cozy/search.py to /home/nathan/cozy/app/lib/python3/dist-packages/cozy
Installing /home/nathan/cozy/cozy/playback_speed.py to /home/nathan/cozy/app/lib/python3/dist-packages/cozy
Installing /home/nathan/cozy/cozy/singleton.py to /home/nathan/cozy/app/lib/python3/dist-packages/cozy
Installing /home/nathan/cozy/cozy/offline_cache.py to /home/nathan/cozy/app/lib/python3/dist-packages/cozy
Installing /home/nathan/cozy/cozy/ui.py to /home/nathan/cozy/app/lib/python3/dist-packages/cozy
Installing /home/nathan/cozy/cozy/search_results.py to /home/nathan/cozy/app/lib/python3/dist-packages/cozy
Installing /home/nathan/cozy/cozy/titlebar.py to /home/nathan/cozy/app/lib/python3/dist-packages/cozy
Installing /home/nathan/cozy/cozy/sleep_timer.py to /home/nathan/cozy/app/lib/python3/dist-packages/cozy
Installing /home/nathan/cozy/cozy/player.py to /home/nathan/cozy/app/lib/python3/dist-packages/cozy
Installing /home/nathan/cozy/cozy/disk_element.py to /home/nathan/cozy/app/lib/python3/dist-packages/cozy
Installing /home/nathan/cozy/cozy/book_element.py to /home/nathan/cozy/app/lib/python3/dist-packages/cozy
Installing /home/nathan/cozy/cozy/tools.py to /home/nathan/cozy/app/lib/python3/dist-packages/cozy
Installing /home/nathan/cozy/cozy/filesystem_monitor.py to /home/nathan/cozy/app/lib/python3/dist-packages/cozy
Installing /home/nathan/cozy/cozy/import_failed_dialog.py to /home/nathan/cozy/app/lib/python3/dist-packages/cozy
Installing /home/nathan/cozy/cozy/file_not_found_dialog.py to /home/nathan/cozy/app/lib/python3/dist-packages/cozy
Installing /home/nathan/cozy/cozy/db.py to /home/nathan/cozy/app/lib/python3/dist-packages/cozy
Installing /home/nathan/cozy/cozy/event_sender.py to /home/nathan/cozy/app/lib/python3/dist-packages/cozy
Installing /home/nathan/cozy/cozy/settings.py to /home/nathan/cozy/app/lib/python3/dist-packages/cozy
Installing /home/nathan/cozy/cozy/artwork_cache.py to /home/nathan/cozy/app/lib/python3/dist-packages/cozy
Installing /home/nathan/cozy/cozy/mpris.py to /home/nathan/cozy/app/lib/python3/dist-packages/cozy
Installing /home/nathan/cozy/cozy/magic/README.md to /home/nathan/cozy/app/lib/python3/dist-packages/cozy/magic
Installing /home/nathan/cozy/cozy/magic/LICENSE to /home/nathan/cozy/app/lib/python3/dist-packages/cozy/magic
Installing /home/nathan/cozy/cozy/magic/magic.py to /home/nathan/cozy/app/lib/python3/dist-packages/cozy/magic
Installing data/img/com.github.geigi.cozy.img.gresource to /home/nathan/cozy/app/share/com.github.geigi.cozy
Installing data/ui/com.github.geigi.cozy.ui.gresource to /home/nathan/cozy/app/share/com.github.geigi.cozy
Installing data/com.github.geigi.cozy.desktop to /home/nathan/cozy/app/share/applications
Installing data/com.github.geigi.cozy.appdata.xml to /home/nathan/cozy/app/share/metainfo
Installing /home/nathan/cozy/data/com.github.geigi.cozy.gschema.xml to /home/nathan/cozy/app/share/glib-2.0/schemas
Installing /home/nathan/cozy/bin/com.github.geigi.cozy to /home/nathan/cozy/app/bin
Running custom install script '/usr/bin/env python3 /home/nathan/cozy/data/meson_post_install.py'
Compiling gsettings schemas...
Updating icon cache...
Running custom install script '/usr/bin/meson --internal gettext install --subdir=po --localedir=share/locale --pkgname=com.github.geigi.cozy'
Installing /home/nathan/cozy/bin/po/en_IE.gmo to /home/nathan/cozy/app/share/locale/en_IE/LC_MESSAGES/com.github.geigi.cozy.mo
Installing /home/nathan/cozy/bin/po/de.gmo to /home/nathan/cozy/app/share/locale/de/LC_MESSAGES/com.github.geigi.cozy.mo
Installing /home/nathan/cozy/bin/po/ru.gmo to /home/nathan/cozy/app/share/locale/ru/LC_MESSAGES/com.github.geigi.cozy.mo
Installing /home/nathan/cozy/bin/po/fr.gmo to /home/nathan/cozy/app/share/locale/fr/LC_MESSAGES/com.github.geigi.cozy.mo
Installing /home/nathan/cozy/bin/po/nl.gmo to /home/nathan/cozy/app/share/locale/nl/LC_MESSAGES/com.github.geigi.cozy.mo
Installing /home/nathan/cozy/bin/po/tr.gmo to /home/nathan/cozy/app/share/locale/tr/LC_MESSAGES/com.github.geigi.cozy.mo
Installing /home/nathan/cozy/bin/po/da_DK.gmo to /home/nathan/cozy/app/share/locale/da_DK/LC_MESSAGES/com.github.geigi.cozy.mo
Installing /home/nathan/cozy/bin/po/es.gmo to /home/nathan/cozy/app/share/locale/es/LC_MESSAGES/com.github.geigi.cozy.mo
Installing /home/nathan/cozy/bin/po/fi.gmo to /home/nathan/cozy/app/share/locale/fi/LC_MESSAGES/com.github.geigi.cozy.mo
Installing /home/nathan/cozy/bin/po/it.gmo to /home/nathan/cozy/app/share/locale/it/LC_MESSAGES/com.github.geigi.cozy.mo
Installing /home/nathan/cozy/bin/po/ms_MY.gmo to /home/nathan/cozy/app/share/locale/ms_MY/LC_MESSAGES/com.github.geigi.cozy.mo
Installing /home/nathan/cozy/bin/po/pl.gmo to /home/nathan/cozy/app/share/locale/pl/LC_MESSAGES/com.github.geigi.cozy.mo
Installing /home/nathan/cozy/bin/po/pt.gmo to /home/nathan/cozy/app/share/locale/pt/LC_MESSAGES/com.github.geigi.cozy.mo
Installing /home/nathan/cozy/bin/po/uk.gmo to /home/nathan/cozy/app/share/locale/uk/LC_MESSAGES/com.github.geigi.cozy.mo
nathan@Nathan:~/cozy$ XDG_DATA_DIRS=/home/nathan/cozy/app/share:$XDG_DATA_DIRS PYTHONPATH=/home/nathan/cozy/app/lib/python3/dist-packages /home/nathan/cozy/app/bin/com.github.geigi.cozy
['/home/nathan/cozy/app/bin/com.github.geigi.cozy']
10:41:08 [MainThread  ] [main      ] [INFO ]  ('elementary', '5.0', 'juno')
10:41:08 [MainThread  ] [main      ] [INFO ]  Starting up cozy 0.6.7
10:41:08 [MainThread  ] [db        ] [ERROR]  Could not connect to database. 
10:41:08 [MainThread  ] [db        ] [ERROR]  Connection already opened.
10:41:08 [MainThread  ] [ui        ] [INFO ]  Initialize main window
10:41:09 [Thread-2    ] [offline_ca] [INFO ]  Startet processing queue
10:41:09 [UpdateDataba] [importer  ] [INFO ]  Total import time: 3.337860107421875e-05
10:41:09 [UpdateDataba] [offline_ca] [INFO ]  Startet processing queue
10:41:44 [MainThread  ] [ui        ] [INFO ]  Closing.
10:41:44 [MainThread  ] [titlebar  ] [INFO ]  Closing.
10:41:44 [MainThread  ] [player    ] [INFO ]  Closing.
10:41:44 [MainThread  ] [db        ] [INFO ]  Closing.
10:41:44 [MainThread  ] [ui        ] [INFO ]  Closing app.
10:41:44 [MainThread  ] [ui        ] [INFO ]  App closed.
```

**Comment by geigi** [comment] 2019-04-09 08:55
Nice! The output looks good! :)

**Comment by NathanBnm** [comment] 2019-04-09 08:58
Do you speak French?  I noticed that you have translated the app into French :smile:
I'm fixing some errors but this is quite good.

**Comment by geigi** [comment] 2019-04-09 09:04
I'd love to speak french but sadly I don't 😅 The translation was a community effort! You can see all the languages and translations on transifex, which is the web platform I setup for people that don't know how to code but want to contribute a translation: https://www.transifex.com/geigi/cozy/

**Comment by geigi** [comment] 2019-04-09 09:06
I just saw your other pull request, I'll merge this one also later today

**Comment by NathanBnm** [comment] 2019-04-09 09:14
Oh I understand :smile: Maybe you'll have to update some stuff about Transifex 'cause I had to make some changes on translations files to improve them.

**Comment by NathanBnm** [comment] 2019-04-09 09:15
> I just saw your other pull request, I'll merge this one also later today

Actually this PR is now out of date, I closed it then

**Comment by NathanBnm** [comment] 2019-04-09 10:12
I still have some issues with translations, when I build the app translations aren't applying

**Comment by geigi** [comment] 2019-04-09 10:29
I don't remember the commands I used to do this myself and I don't have access to my linux machine I used for this until next week ... Here is some information, maybe you can figure it out. Next week I'm able to look up the commands in the bash history of that machine.

1. Add the file you want to translate to `po/POTFILES`
2. You have to run `xgettext` with some set of arguments. The template file is `po/cozy.pot`
3. Next thing I did was push the new template to transifex. I did all the translation there and pulled the translated files into the repository. I think you can use `msginit` to do this on your local machine, but I don't know how to use this tool.

Here is a tutorial I found for those two tools, maybe it's helpful for you: http://www.labri.fr/perso/fleury/posts/programming/a-quick-gettext-tutorial.html

Also you have to run the `ninja build` command again after changing the translation. Good luck! Otherwise I'll be able to help you next week.

**Comment by NathanBnm** [comment] 2019-04-09 10:45
I think it's not really the issue yet. I already built the app with translations.

I used the following commands:
```bash
ninja com.github.geigi.cozy-update-po
ninja extra-update-po
```
And then I built the app again, and `mo` files are correctly generating, but it seems that the app isn't using them.

**Comment by geigi** [comment] 2019-04-09 11:04
Cool, I didn't know those commands yet:
```
ninja com.github.geigi.cozy-update-po
ninja extra-update-po
```

I'll have a look, maybe I can reproduce this issue. To be honest I rarely tested the translations with cozy, so this might be an issue happening on every machine.

**Comment by NathanBnm** [comment] 2019-04-09 11:34
Actually those commands are automatically making the operations you noticed me.

**Comment by geigi** [comment] 2019-04-09 12:08
I just tried this on my machine and it is working fine (at least with running `ninja build`). When I try the commands you provided I get the following errors:
```
ninja: error: unknown target 'com.github.geigi.cozy-update-po'
ninja: error: unknown target 'extra-update-po'
```

**Comment by NathanBnm** [comment] 2019-04-09 12:43
Did you tried with my forked repo? Because basically you're package isn't named `com.github.geigi.cozy` but only `cozy`, I had to change that. And the `extra` target doesn't exist in your repo, only in mine for now :smile:

Feel free to ask if it's not very clear for you

**Comment by geigi** [comment] 2019-04-09 14:07
Ah I see, I just tried your fork.

I could not build cozy with your branch, because you added `vala` and `c` to the `meson.build` file, but cozy isn't using any vala or c code and doesn't need the compiler. After I removed this I was able to build cozy again.

With your fork the translations are also not working for me. I don't know what happened there, but they aren't working at all for me (german translation). It always displays the English texts. I scrolled through your commits but I could not find what might be wrong there... I suspect it could be something in line `conf.set('LOCALE_DIR', join_paths(get_option('prefix'), get_option('datadir'), 'locale'))` in meson.build. As you changed the project name maybe something with setting the locale dir is not working properly anymore. Maybe you can debug from here.

I have another suggestion: You added a lot of empty translation files. I would prefer to only have the languages added to the project where a translation actually exists. The reason for this is because transifex works this way (it creates only language files where a translation exists) and it is also way less cluttery. Hope this helps!

**Comment by NathanBnm** [comment] 2019-04-10 09:24
>
> I could not build cozy with your branch, because you added `vala` and `c` to the `meson.build` file, but cozy isn't using any vala or c code and doesn't need the compiler. After I removed this I was able to build cozy again.

You're right, I fixed this.

> 
> With your fork the translations are also not working for me. I don't know what happened there, but they aren't working at all for me (german translation). It always displays the English texts. I scrolled through your commits but I could not find what might be wrong there... I suspect it could be something in line `conf.set('LOCALE_DIR', join_paths(get_option('prefix'), get_option('datadir'), 'locale'))` in meson.build. As you changed the project name maybe something with setting the locale dir is not working properly anymore. Maybe you can debug from here.

Yes it's the same for me with French. But did you try with your repo ? Were the translations working before ? I checked this and it seems that the locale directory is correctly configured, so it seems not to be the issue. I don't really know where it comes from.

I made some other fixes, I deleted `project_name` and `project_id` which were useless actually. I replaced one with `meson.project_name()` (which is `com.github.geigi.cozy`).

> 
> I have another suggestion: You added a lot of empty translation files. I would prefer to only have the languages added to the project where a translation actually exists. The reason for this is because transifex works this way (it creates only language files where a translation exists) and it is also way less cluttery. Hope this helps!

In fact, a lot of apps, including elementary OS apps are doing this. This prevent people to create invalid translation files. Actually Transifex doesn't properly format files to. For example "da_DK", "en_IE", "ms_MY" and "zh_CN" aren't correct languages codes. "en_IE" doesn't exist and the others should be "da", "ms" and "zh". It's like "fr" and "fr_CA", "fr" is for French (France), and "fr_CA" is for French (Canada). Therefore "da_DK" shouldn't exist for example. Let me know if it's not clear for you.

I don't really like Transifex, I find it not easy to use. Like elementary does I prefer to use Weblate. I find this easier to manage. Maybe you can take a look at this.

Of course it's up to you to decide what you want to use.

**Comment by NathanBnm** [comment] 2019-04-10 11:58
I tried to add the following line:

```meson
add_global_arguments('-DGETTEXT_PACKAGE="@0@"'.format (meson.project_name()), language:'py')
```

I tried with 'py' and 'python' but it' not working.

**Comment by geigi** [comment] 2019-04-11 08:22
I tried it with my repo and it is working fine... I have no idea what's happening there and why it is not working...

I'm pretty sure that those are valid language codes. Have a look at `/usr/share/i18n/SUPPORTED` and those codes should be included. `en_IE` is the international English code if I understand this correctly. But I understand your point with `da_DK`. On the other hand those codes seem to work fine for my users.

To be honest I didn't compare transifex to different services. Now over 30 people are translating cozy on transifex therefore I will stick to that, at least for now :) but thanks for all this information :)

**Comment by NathanBnm** [comment] 2019-04-11 10:10
I don't really know why either :confused: I'm still looking for this, maybe you can have a look to your commands next week when you can as you said.

In fact International English should be English from United Kingdom, it's the default languages of the apps, that's why `en` should not be created when translating an app, it will be repetitive. I understand your point :smile: I'm just setting up things like elementary OS developers does.

Yes sure, if you already have translators on Transifex your alright.

**Comment by NathanBnm** [comment] 2019-04-11 10:29
@geigi I just found out how to resolve this issue. It was in the `main.py` script where I had to replace `cozy` by `com.github.geigi.cozy` in the gettext instructions :smile:

I still have to make some test but I will do a PR soon :+1:

**Closed** 2019-06-10 15:34 UTC
Labels: Translation
